-- Pin High — migration 12: real course descriptions (~136 courses)
-- Run once in Supabase SQL Editor.

update courses set description = 'Established parkland in Sandton''s leafy suburbs — tight, tree-lined and a long-standing fixture of northern Joburg golf.' where slug = 'bryanston';
update courses set description = 'Classic West Rand parkland, one of Johannesburg''s older clubs, known for friendly golf and honest value.' where slug = 'cmr';
update courses set description = 'The second course on Country Club Johannesburg''s Woodmead estate — shorter and sportier than its championship sibling.' where slug = 'country-club-johannesburg-rocklands';
update courses set description = 'Gary Player-designed estate parkland along the Jukskei in Fourways, sharing a boundary with Steyn City.' where slug = 'dainfern';
update courses set description = 'Modern estate course wrapped around a quarry canyon on the West Rand, with dramatic elevation changes and water in play.' where slug = 'eagle-canyon';
update courses set description = 'Vaal Triangle parkland in Vanderbijlpark with mature trees and a strong competitive tradition.' where slug = 'emfuleni';
update courses set description = 'Greg Norman signature estate south of Johannesburg — one of very few Norman designs in Africa, long and links-flavoured.' where slug = 'eye-of-africa';
update courses set description = 'Rolling parkland in the Klipriviersberg foothills of southern Joburg, with more elevation change than most highveld courses.' where slug = 'glenvista';
update courses set description = 'West Wits mining-belt parkland in Westonaria, a stalwart of far West Rand golf.' where slug = 'goldfields-west';
update courses set description = 'Revived public parkland in Linksfield sharing a fence with Royal Johannesburg — Joburg''s favourite pay-and-play.' where slug = 'huddle-park';
update courses set description = 'Estate course in North Riding with wetlands and water shaping the closing stretch.' where slug = 'jackal-creek';
update courses set description = 'Historic parkland in the heart of Johannesburg''s northern suburbs — tight, treed and wonderfully walkable.' where slug = 'killarney';
update courses set description = 'West Rand parkland with big trees and quick kikuyu, serving Mogale City golfers for generations.' where slug = 'krugersdorp';
update courses set description = 'Midrand parkland neighbouring the famous grand prix circuit, well conditioned year-round.' where slug = 'kyalami';
update courses set description = 'Parkland threaded through the old dynamite-factory estate''s plantations east of Johannesburg.' where slug = 'modderfontein';
update courses set description = 'One of Johannesburg''s oldest layouts — a compact ridge-top parkland with city views.' where slug = 'observatory';
update courses set description = 'Beloved Joburg parkland beneath the Westcliff ridge, famous for towering trees and its walkability.' where slug = 'parkview';
update courses set description = 'Randpark''s second championship course, co-host of the Joburg Open alongside Firethorn.' where slug = 'randpark-bushwillow';
update courses set description = 'Riverside parkland on the banks of the Vaal at Vereeniging — a golf-weekend favourite for decades.' where slug = 'riviera-on-vaal';
update courses set description = 'The classic older sibling of the East course at Royal Johannesburg & Kensington — shorter and full of charm.' where slug = 'royal-johannesburg-kensington-west';
update courses set description = 'Spacious West Rand parkland at Roodepoort with ridge-line backdrops.' where slug = 'ruimsig';
update courses set description = 'Estate parkland beside Irene''s pastures in Centurion, with a genteel country feel.' where slug = 'southdowns';
update courses set description = 'The home of golf in Soweto — a proud, community-driven club that has produced generations of township golfers.' where slug = 'soweto';
update courses set description = 'City parkland within the famous Wanderers sporting precinct in Illovo.' where slug = 'wanderers';
update courses set description = 'East Rand parkland with a strong championship pedigree and lakes-district setting.' where slug = 'benoni';
update courses set description = 'Links-style estate at Benoni with water everywhere — among Gauteng''s best-conditioned modern courses.' where slug = 'ebotse-links';
update courses set description = 'The old East Rand Proprietary Mines club in Boksburg — big trees, mining history and honest parkland golf.' where slug = 'erpm';
update courses set description = 'Established parkland near OR Tambo, a popular society-golf venue on the East Rand.' where slug = 'kempton-park';
update courses set description = 'Far East Rand country parkland with quiet fairways and a welcoming clubhouse.' where slug = 'nigel';
update courses set description = 'Springs parkland set among old bluegums, a stalwart of East Rand golf.' where slug = 'pollak-park';
update courses set description = 'Alberton parkland with plenty of water in play.' where slug = 'reading';
update courses set description = 'Big classical tree-lined parkland, one of the East Rand''s traditional championship tests.' where slug = 'springs';
update courses set description = 'Brakpan''s mining-heritage parkland — generous fairways under mature gums.' where slug = 'state-mines';
update courses set description = 'Golf beside Benoni''s famous lakes — relaxed parkland with water views.' where slug = 'the-lake-club-benoni';
update courses set description = 'Pretoria North parkland with bushveld touches, a stalwart of Gauteng North golf.' where slug = 'akasia';
update courses set description = 'Gary Player signature estate in Midrand with sweeping water features and immaculate conditioning.' where slug = 'blue-valley';
update courses set description = 'Parkland along the Hennops River in the heart of Centurion, water threading the back nine.' where slug = 'centurion';
update courses set description = 'Historic parkland on the old Smuts-country estate at Irene — oaks, pastures and charm.' where slug = 'irene';
update courses set description = 'Bushveld golf village northeast of Pretoria, rocky outcrops framing the holes.' where slug = 'pebble-rock';
update courses set description = 'The capital''s grande dame at Waterkloof — championship parkland with a storied amateur history.' where slug = 'pretoria';
update courses set description = 'One of Pretoria''s oldest clubs, a classic city parkland west of the CBD.' where slug = 'pretoria-golf-club';
update courses set description = 'The old military club at Thaba Tshwane — no-frills parkland with deep golfing tradition.' where slug = 'services';
update courses set description = 'Estate parkland along the Pienaars River in Pretoria East, water on half the holes.' where slug = 'silver-lakes';
update courses set description = 'Ernie Els signature design at Centurion — one of the longest tests in the country from the tips, yet playable from sensible tees.' where slug = 'the-els-club-copperleaf';
update courses set description = 'Ridge-top parkland above Pretoria''s southern suburbs with views across the capital.' where slug = 'waterkloof';
update courses set description = 'Championship parkland in Pretoria East, a regular host of top amateur events.' where slug = 'wingate-park';
update courses set description = 'Residential estate championship course in Pretoria East — manicured and water-lined.' where slug = 'woodhill';
update courses set description = 'True bushveld golf at Mookgophong, thorn trees framing every hole.' where slug = 'kameeldoring';
update courses set description = 'Bushveld estate at Modimolle beneath the Waterberg, with giraffe and zebra beyond the fairway lines.' where slug = 'koro-creek';
update courses set description = 'Lephalale''s bushveld course — a green oasis in coal country.' where slug = 'mogol';
update courses set description = 'Limpopo''s capital-city championship parkland and provincial tournament host.' where slug = 'polokwane';
update courses set description = 'Subtropical parkland in the Letaba valley — lush, hilly and green year-round.' where slug = 'tzaneen';
update courses set description = 'Highveld town parkland with big skies and honest golf.' where slug = 'ermelo';
update courses set description = 'Casino-resort course at Secunda, styled with water and links touches.' where slug = 'graceland';
update courses set description = 'The Lowveld capital''s parkland — tropical trees and quick greens on the Kruger corridor.' where slug = 'mbombela';
update courses set description = 'Coalfields parkland with mature trees and a strong club culture.' where slug = 'middelburg-mpumalanga';
update courses set description = 'Resort parkland on the Sabie River at Hazyview — hippos and crocodiles occasionally in the gallery.' where slug = 'sabi-river-sun';
update courses set description = 'Sasol-country parkland at Evander, a friendly highveld club.' where slug = 'walker-park';
update courses set description = 'eMalahleni''s championship parkland, long a force in Mpumalanga amateur golf.' where slug = 'witbank';
update courses set description = 'Goldfields parkland, one of the North West''s traditional championship venues.' where slug = 'klerksdorp';
update courses set description = 'Resort course curling along the Magalies River below the mountains at Hartbeespoort.' where slug = 'magalies-park';
update courses set description = 'Mining-town parkland with a proud Vaal River district history.' where slug = 'orkney';
update courses set description = 'University-town parkland with mature oaks and a strong student golf tradition.' where slug = 'potchefstroom';
update courses set description = 'Parkland at the foot of the Magaliesberg on the bushveld''s edge.' where slug = 'rustenburg';
update courses set description = 'Eco-estate resort course in the Hartbeespoort hills.' where slug = 'seasons-eco';
update courses set description = 'Winelands golf-and-wine estate outside Stellenbosch — vines beside the fairways and a cellar at the clubhouse.' where slug = 'devonvale';
update courses set description = 'West Coast links-style estate above the Langebaan lagoon — firm, windy and fun.' where slug = 'langebaan-country-estate';
update courses set description = 'Breede Valley country course among vineyards, a wine-route favourite.' where slug = 'robertson';
update courses set description = 'Historic oak-lined parkland in the university town — among the Cape''s prettiest inland courses.' where slug = 'stellenbosch';
update courses set description = 'Breede Valley parkland ringed by mountains, a Boland stalwart.' where slug = 'worcester';
update courses set description = 'The Garden Route''s beloved traditional parkland — towering trees, true greens and famous value.' where slug = 'george';
update courses set description = 'Modern championship estate on George''s outskirts with Outeniqua mountain views.' where slug = 'kingswood';
update courses set description = 'Lagoon-side parkland below the Knysna Heads — short, tight and full of charm.' where slug = 'knysna';
update courses set description = 'Clifftop course above the Indian Ocean, sea views from nearly every hole and whales in season.' where slug = 'mossel-bay';
update courses set description = 'Klein Karoo parkland in ostrich country — an oasis of green beneath big mountains.' where slug = 'oudtshoorn';
update courses set description = 'Country club above the Keurbooms lagoon with Tsitsikamma views.' where slug = 'plettenberg-bay';
update courses set description = 'Northern-suburbs parkland, a Cape Town stalwart with quick greens.' where slug = 'bellville';
update courses set description = 'Rolling parkland among the Durbanville wine hills — wind, views and value.' where slug = 'durbanville';
update courses set description = 'Classic Cape parkland and historic SA Open venue, with Table Mountain on the horizon.' where slug = 'king-david-mowbray';
update courses set description = 'Friendly northern-suburbs parkland along the Kuils River.' where slug = 'kuils-river';
update courses set description = 'Compact parkland beneath the Tygerberg — honest value golf.' where slug = 'parow';
update courses set description = 'Southern-suburbs parkland along the Black River, Devil''s Peak looming over every hole.' where slug = 'rondebosch';
update courses set description = 'Helderberg-basin parkland of oaks and mountain views on the winelands'' edge.' where slug = 'somerset-west';
update courses set description = 'Seaside-town parkland at the foot of the Hottentots Holland mountains.' where slug = 'strand';
update courses set description = 'Coastal parkland south of Durban with subtropical bush and sea breezes.' where slug = 'amanzimtoti';
update courses set description = 'Durban''s Bluff course amid coastal forest — monkeys included.' where slug = 'bluff-national-park';
update courses set description = 'Country course on the Midlands edge between Durban and Pietermaritzburg.' where slug = 'cato-ridge';
update courses set description = 'Resort golf beneath the Drakensberg amphitheatre — arguably SA''s most scenic mountain backdrop.' where slug = 'champagne-sports-resort';
update courses set description = 'Rolling estate parkland at Hillcrest, among KZN''s best-conditioned modern courses.' where slug = 'cotswold-downs';
update courses set description = 'Mountain resort course in the southern Berg — crisp air and trout-stream country.' where slug = 'drakensberg-gardens';
update courses set description = 'Battlefields-country parkland in northern KZN.' where slug = 'dundee';
update courses set description = 'Zululand parkland wrapped in lush coastal vegetation.' where slug = 'empangeni';
update courses set description = 'Golf on the edge of the indigenous Dlinza forest at Eshowe.' where slug = 'eshowe-hills';
update courses set description = 'A Midlands gem at Nottingham Road — bentgrass greens and trout-country views.' where slug = 'gowrie-farm';
update courses set description = 'Gorge-side parkland in the Upper Highway — forested, cool and green.' where slug = 'kloof';
update courses set description = 'South Coast holiday golf — compact, fun and breezy.' where slug = 'margate';
update courses set description = 'Founded in 1886 and the site of some of South Africa''s earliest golf.' where slug = 'maritzburg';
update courses set description = 'Northern KZN parkland below the Drakensberg foothills.' where slug = 'newcastle';
update courses set description = 'Durban course named for the legendary Papwa Sewgolum — golf history in every sense.' where slug = 'papwa-sewgolum';
update courses set description = 'South Coast course with one of the country''s largest club memberships, and ocean views to match.' where slug = 'port-shepstone';
update courses set description = 'Coastal parkland near the harbour — short on the card, tricky in the wind.' where slug = 'richards-bay';
update courses set description = 'Utterly unique: a parkland laid out inside the Greyville racecourse oval in central Durban.' where slug = 'royal-durban';
update courses set description = 'South Coast favourite and the country''s shortest full 18 — endless fun in the sea air.' where slug = 'scottburgh';
update courses set description = 'Executive-style course at Ballito with thirteen par 3s — the country''s cleverest short course.' where slug = 'simbithi';
update courses set description = 'Forest-and-sea parkland at Pennington, whales sometimes on view from the 19th.' where slug = 'umdoni-park';
update courses set description = 'North Coast country club among sugar cane and coastal bush.' where slug = 'umhlali';
update courses set description = 'Clifftop village course on the South Coast, railway line and salt air part of the furniture.' where slug = 'umkomaas';
update courses set description = 'Pietermaritzburg parkland with a proud championship history.' where slug = 'victoria';
update courses set description = 'Estate course beneath the Drakensberg foothills at Newcastle.' where slug = 'vulintaba';
update courses set description = 'Durban''s municipal stalwart, a road''s width away from Durban Country Club.' where slug = 'windsor-park';
update courses set description = 'Eastern Free State parkland in Golden Gate country.' where slug = 'bethlehem';
update courses set description = 'Highland golf village ringed by sandstone cliffs — the Free State''s prettiest setting.' where slug = 'clarens';
update courses set description = 'Cherry-country course on the Lesotho border.' where slug = 'ficksburg';
update courses set description = 'One of South Africa''s oldest country clubs, founded 1887, beneath the Platberg.' where slug = 'harrismith';
update courses set description = 'Vaal River estate at Sasolburg with links leanings.' where slug = 'heron-banks';
update courses set description = 'Northern Free State parkland stalwart.' where slug = 'kroonstad';
update courses set description = 'Border-country course beneath sandstone koppies.' where slug = 'ladybrand';
update courses set description = 'Grand old Vaal River parkland — generations of championship golf under giant trees.' where slug = 'maccauvlei';
update courses set description = 'Welkom''s goldfields parkland, built in the mining boom years.' where slug = 'oppenheimer-park';
update courses set description = 'Estate course on the Vaal at Parys — river frontage and weekend-town charm.' where slug = 'parys-golf-country-estate';
update courses set description = 'Bloemfontein''s championship parkland, sharing a boundary with Bloemfontein Golf Club.' where slug = 'schoeman-park';
update courses set description = 'Vaal River estate golf with water on both nines.' where slug = 'vaal-de-grace';
update courses set description = 'Hantam Karoo course — remote, characterful and proudly maintained.' where slug = 'calvinia';
update courses set description = 'Upper Karoo town course — genuine frontier golf.' where slug = 'carnarvon';
update courses set description = 'Golf on the 1899 Anglo-Boer battlefield outside Kimberley — history in every bunker.' where slug = 'magersfontein';
update courses set description = 'Orange River oasis among vineyards on the Kalahari''s edge.' where slug = 'upington';
update courses set description = 'Karoo heartland course serving its district for generations.' where slug = 'victoria-west';
update courses set description = 'Mountain eco-estate in the Winterberg — highland golf with forest and game.' where slug = 'katberg-eco';
update courses set description = 'The championship course of the old Transkei interior.' where slug = 'mthatha';
update courses set description = 'Modern estate design outside East London, laid out among olive groves.' where slug = 'olivewood';
update courses set description = 'Komani''s traditional parkland, a border-country stalwart.' where slug = 'queenstown';
update courses set description = 'East London classic with links leanings beside the Buffalo River mouth.' where slug = 'west-bank';
update courses set description = 'One of only a handful of Royal clubs in South Africa — charming duneland golf at the Kowie.' where slug = 'royal-port-alfred';
update courses set description = 'The village course among the canals — short, breezy and beloved.' where slug = 'st-francis-bay';
update courses set description = 'Makhanda''s course in the Belmont Valley along the Bloukrans.' where slug = 'the-belmont';
update courses set description = 'Kariega parkland, one of the Eastern Cape''s oldest clubs.' where slug = 'uitenhage';

-- Remaining auto-template courses get a warmer honest line
update courses set description =
  'A ' || holes || '-hole country course in ' || town ||
  ' — the kind of local club that keeps South African golf alive. Played it? Add a rating and put it on the map.'
where description like '%GolfRSA-affiliated. Played here?%';
