-- FairwayRank ZA — migration 2: full GolfRSA course list (360 new courses)
-- Run once in Supabase SQL Editor.

drop view if exists course_rankings;

alter table courses add column if not exists holes int not null default 18;

create view course_rankings with (security_invoker = on) as
select
  c.*,
  count(r.id)::int as n_ratings,
  coalesce(avg(r.overall), 0) as avg_overall
from courses c
left join ratings r on r.course_id = c.id
group by c.id;

insert into courses (slug, name, town, province, access, holes) values
('bryanston','Bryanston Country Club','Johannesburg','Gauteng','Members & visitors',18),
('cmr','CMR Golf Club','Roodepoort','Gauteng','Members & visitors',18),
('country-club-johannesburg-rocklands','Country Club Johannesburg (Rocklands)','Johannesburg','Gauteng','Members & visitors',18),
('dainfern','Dainfern Golf Estate','Fourways','Gauteng','Members & visitors',18),
('eagle-canyon','Eagle Canyon Golf Estate','Roodepoort','Gauteng','Members & visitors',18),
('emfuleni','Emfuleni Golf Estate','Vanderbijlpark','Gauteng','Members & visitors',18),
('eye-of-africa','Eye of Africa Golf Estate','Eikenhof','Gauteng','Members & visitors',18),
('glenvista','Glenvista Country Club','Johannesburg','Gauteng','Members & visitors',18),
('goldfields-west','Goldfields West Golf Club','Westonaria','Gauteng','Members & visitors',18),
('huddle-park','Huddle Park Golf Club','Johannesburg','Gauteng','Members & visitors',18),
('jackal-creek','Jackal Creek Golf Estate','Roodepoort','Gauteng','Members & visitors',18),
('killarney','Killarney Country Club','Johannesburg','Gauteng','Members & visitors',18),
('krugersdorp','Krugersdorp Golf Club','Krugersdorp','Gauteng','Members & visitors',18),
('kyalami','Kyalami Country Club','Midrand','Gauteng','Members & visitors',18),
('meyerton','Meyerton Golf Club','Meyerton','Gauteng','Members & visitors',18),
('modderfontein','Modderfontein Golf Club','Modderfontein','Gauteng','Members & visitors',18),
('observatory','Observatory Golf Club','Johannesburg','Gauteng','Members & visitors',18),
('parkview','Parkview Golf Club','Johannesburg','Gauteng','Members & visitors',18),
('randpark-bushwillow','Randpark (Bushwillow)','Johannesburg','Gauteng','Members & visitors',18),
('riviera-on-vaal','Riviera on Vaal Country Club','Vereeniging','Gauteng','Members & visitors',18),
('royal-johannesburg-kensington-west','Royal Johannesburg & Kensington (West)','Johannesburg','Gauteng','Members & visitors',18),
('ruimsig','Ruimsig Country Club','Roodepoort','Gauteng','Members & visitors',18),
('southdowns','Southdowns Country Club','Centurion','Gauteng','Members & visitors',18),
('soweto','Soweto Country Club','Soweto','Gauteng','Members & visitors',18),
('wanderers','Wanderers Golf Club','Johannesburg','Gauteng','Members & visitors',18),
('benoni','Benoni Country Club','Benoni','Gauteng','Members & visitors',18),
('ebotse-links','Ebotse Links','Benoni','Gauteng','Members & visitors',18),
('erpm','ERPM Golf Club','Boksburg','Gauteng','Members & visitors',18),
('germiston','Germiston Golf Club','Germiston','Gauteng','Members & visitors',18),
('kempton-park','Kempton Park Golf Club','Kempton Park','Gauteng','Members & visitors',18),
('nigel','Nigel Golf Club','Nigel','Gauteng','Members & visitors',18),
('pollak-park','Pollak Park Golf Club','Springs','Gauteng','Members & visitors',18),
('reading','Reading Country Club','Alberton','Gauteng','Members & visitors',18),
('royal-oak','Royal Oak Country Club','Alberton','Gauteng','Members & visitors',18),
('springs','Springs Country Club','Springs','Gauteng','Members & visitors',18),
('state-mines','State Mines Country Club','Brakpan','Gauteng','Members & visitors',18),
('the-lake-club-benoni','The Lake Club Benoni','Benoni','Gauteng','Members & visitors',18),
('akasia','Akasia Golf Club','Pretoria','Gauteng','Members & visitors',18),
('blue-valley','Blue Valley Golf Estate','Midrand','Gauteng','Members & visitors',18),
('bronkhorstspruit','Bronkhorstspruit Golf Club','Bronkhorstspruit','Gauteng','Members & visitors',18),
('centurion','Centurion Country Club','Centurion','Gauteng','Members & visitors',18),
('irene','Irene Country Club','Centurion','Gauteng','Members & visitors',18),
('pebble-rock-golf-village','Pebble Rock Golf Village','Pretoria','Gauteng','Members & visitors',18),
('pretoria','Pretoria Country Club','Pretoria','Gauteng','Members & visitors',18),
('pretoria-golf-club','Pretoria Golf Club','Pretoria','Gauteng','Members & visitors',18),
('services','Services Golf Club','Thaba Tshwane','Gauteng','Members & visitors',18),
('silver-lakes','Silver Lakes Golf Estate','Pretoria','Gauteng','Members & visitors',18),
('the-els-club-copperleaf','The Els Club Copperleaf','Centurion','Gauteng','Members & visitors',18),
('waterkloof','Waterkloof Golf Club','Pretoria','Gauteng','Members & visitors',18),
('wingate-park','Wingate Park Country Club','Pretoria','Gauteng','Members & visitors',18),
('woodhill','Woodhill Golf Estate','Pretoria','Gauteng','Members & visitors',18),
('kameeldoring','Kameeldoring Golf Club','Mookgophong','Limpopo','Members & visitors',18),
('koro-creek-bushveld','Koro Creek Bushveld Golf Estate','Modimolle','Limpopo','Members & visitors',18),
('mogol','Mogol Golf Club','Lephalale','Limpopo','Members & visitors',18),
('polokwane','Polokwane Golf Club','Polokwane','Limpopo','Members & visitors',18),
('tzaneen','Tzaneen Country Club','Tzaneen','Limpopo','Members & visitors',18),
('ermelo','Ermelo Golf Club','Ermelo','Mpumalanga','Members & visitors',18),
('graceland','Graceland Golf Course','Secunda','Mpumalanga','Members & visitors',18),
('mbombela','Mbombela Golf Club','Mbombela','Mpumalanga','Members & visitors',18),
('middelburg-mpumalanga','Middelburg Golf Club','Middelburg','Mpumalanga','Members & visitors',18),
('sabi-river-sun','Sabi River Sun Golf Course','Hazyview','Mpumalanga','Members & visitors',18),
('walker-park','Walker Park Golf Club','Evander','Mpumalanga','Members & visitors',18),
('witbank','Witbank Golf Club','eMalahleni','Mpumalanga','Members & visitors',18),
('klerksdorp','Klerksdorp Golf Club','Klerksdorp','North West','Members & visitors',18),
('magalies-park','Magalies Park Golf Club','Hartbeespoort','North West','Members & visitors',18),
('orkney','Orkney Golf Club','Orkney','North West','Members & visitors',18),
('potchefstroom','Potchefstroom Golf Club','Potchefstroom','North West','Members & visitors',18),
('rustenburg','Rustenburg Golf Club','Rustenburg','North West','Members & visitors',18),
('seasons-eco','Seasons Eco Golf Estate','Hartbeespoort','North West','Members & visitors',18),
('devonvale-golf-wine-estate','Devonvale Golf & Wine Estate','Stellenbosch','Western Cape','Members & visitors',18),
('hermanus','Hermanus Golf Club','Hermanus','Western Cape','Members & visitors',18),
('langebaan-country-estate','Langebaan Country Estate','Langebaan','Western Cape','Members & visitors',18),
('paarl','Paarl Golf Club','Paarl','Western Cape','Members & visitors',18),
('robertson','Robertson Golf Club','Robertson','Western Cape','Members & visitors',18),
('stellenbosch','Stellenbosch Golf Club','Stellenbosch','Western Cape','Members & visitors',18),
('worcester','Worcester Golf Club','Worcester','Western Cape','Members & visitors',18),
('george','George Golf Club','George','Western Cape','Members & visitors',18),
('kingswood','Kingswood Golf Estate','George','Western Cape','Members & visitors',18),
('knysna','Knysna Golf Club','Knysna','Western Cape','Members & visitors',18),
('mossel-bay','Mossel Bay Golf Club','Mossel Bay','Western Cape','Members & visitors',18),
('oudtshoorn','Oudtshoorn Golf Club','Oudtshoorn','Western Cape','Members & visitors',18),
('plettenberg-bay','Plettenberg Bay Country Club','Plettenberg Bay','Western Cape','Members & visitors',18),
('bellville','Bellville Golf Club','Cape Town','Western Cape','Members & visitors',18),
('durbanville','Durbanville Golf Club','Cape Town','Western Cape','Members & visitors',18),
('king-david-mowbray','King David Mowbray Golf Club','Cape Town','Western Cape','Members & visitors',18),
('kuils-river','Kuils River Golf Club','Cape Town','Western Cape','Members & visitors',18),
('parow','Parow Golf Club','Cape Town','Western Cape','Members & visitors',18),
('rondebosch','Rondebosch Golf Club','Cape Town','Western Cape','Members & visitors',18),
('somerset-west','Somerset West Golf Club','Somerset West','Western Cape','Members & visitors',18),
('strand','Strand Golf Club','Strand','Western Cape','Members & visitors',18),
('amanzimtoti','Amanzimtoti Country Club','Amanzimtoti','KwaZulu-Natal','Members & visitors',18),
('bluff-national-park','Bluff National Park Golf Club','Durban','KwaZulu-Natal','Members & visitors',18),
('cato-ridge','Cato Ridge Country Club','Cato Ridge','KwaZulu-Natal','Members & visitors',18),
('champagne-sports-resort','Champagne Sports Resort','Winterton','KwaZulu-Natal','Resort',18),
('cotswold-downs','Cotswold Downs Golf Estate','Hillcrest','KwaZulu-Natal','Members & visitors',18),
('drakensberg-gardens-golf-resort','Drakensberg Gardens Golf Resort','Underberg','KwaZulu-Natal','Resort',18),
('dundee','Dundee Golf Club','Dundee','KwaZulu-Natal','Members & visitors',18),
('empangeni','Empangeni Golf Club','Empangeni','KwaZulu-Natal','Members & visitors',18),
('eshowe-hills','Eshowe Hills Golf Estate','Eshowe','KwaZulu-Natal','Members & visitors',18),
('gowrie-farm','Gowrie Farm Golf Club','Nottingham Road','KwaZulu-Natal','Members & visitors',18),
('kloof','Kloof Country Club','Kloof','KwaZulu-Natal','Members & visitors',18),
('margate','Margate Country Club','Margate','KwaZulu-Natal','Members & visitors',18),
('maritzburg','Maritzburg Golf Club','Pietermaritzburg','KwaZulu-Natal','Members & visitors',18),
('newcastle','Newcastle Golf Club','Newcastle','KwaZulu-Natal','Members & visitors',18),
('papwa-sewgolum','Papwa Sewgolum Golf Course','Durban','KwaZulu-Natal','Members & visitors',18),
('port-shepstone','Port Shepstone Country Club','Port Shepstone','KwaZulu-Natal','Members & visitors',18),
('richards-bay','Richards Bay Country Club','Richards Bay','KwaZulu-Natal','Members & visitors',18),
('royal-durban','Royal Durban Golf Club','Durban','KwaZulu-Natal','Members & visitors',18),
('scottburgh','Scottburgh Golf Club','Scottburgh','KwaZulu-Natal','Members & visitors',18),
('simbithi','Simbithi Country Club','Ballito','KwaZulu-Natal','Members & visitors',18),
('umdoni-park','Umdoni Park Golf Club','Pennington','KwaZulu-Natal','Members & visitors',18),
('umhlali','Umhlali Country Club','Ballito','KwaZulu-Natal','Members & visitors',18),
('umkomaas','Umkomaas Golf Club','Umkomaas','KwaZulu-Natal','Members & visitors',18),
('victoria','Victoria Country Club','Pietermaritzburg','KwaZulu-Natal','Members & visitors',18),
('vulintaba','Vulintaba Country Club','Newcastle','KwaZulu-Natal','Members & visitors',18),
('windsor-park','Windsor Park Golf Club','Durban','KwaZulu-Natal','Members & visitors',18),
('bethlehem','Bethlehem Golf Club','Bethlehem','Free State','Members & visitors',18),
('clarens','Clarens Golf Estate','Clarens','Free State','Members & visitors',18),
('ficksburg','Ficksburg Golf Club','Ficksburg','Free State','Members & visitors',18),
('harrismith','Harrismith Golf Club','Harrismith','Free State','Members & visitors',18),
('heron-banks','Heron Banks Golf Estate','Sasolburg','Free State','Members & visitors',18),
('kroonstad','Kroonstad Golf Club','Kroonstad','Free State','Members & visitors',18),
('ladybrand','Ladybrand Golf Club','Ladybrand','Free State','Members & visitors',18),
('maccauvlei','Maccauvlei Golf Club','Vereeniging','Free State','Members & visitors',18),
('oppenheimer-park','Oppenheimer Park Golf Club','Welkom','Free State','Members & visitors',18),
('parys-golf-country-estate','Parys Golf & Country Estate','Parys','Free State','Members & visitors',18),
('schoeman-park','Schoeman Park Golf Club','Bloemfontein','Free State','Members & visitors',18),
('vaal-de-grace','Vaal de Grace Golf Estate','Parys','Free State','Members & visitors',18),
('calvinia','Calvinia Golf Club','Calvinia','Northern Cape','Members & visitors',18),
('carnarvon','Carnarvon Golf Club','Carnarvon','Northern Cape','Members & visitors',18),
('magersfontein-memorial','Magersfontein Memorial Golf Course','Kimberley','Northern Cape','Members & visitors',18),
('upington','Upington Golf Club','Upington','Northern Cape','Members & visitors',18),
('victoria-west','Victoria West Golf Club','Victoria West','Northern Cape','Members & visitors',18),
('katberg-eco','Katberg Eco Golf Estate','Katberg','Eastern Cape','Members & visitors',18),
('mthatha','Mthatha Golf Club','Mthatha','Eastern Cape','Members & visitors',18),
('olivewood','Olivewood Golf Estate','East London','Eastern Cape','Members & visitors',18),
('queenstown','Queenstown Golf Club','Komani','Eastern Cape','Members & visitors',18),
('west-bank','West Bank Golf Club','East London','Eastern Cape','Members & visitors',18),
('royal-port-alfred','Royal Port Alfred Golf Club','Port Alfred','Eastern Cape','Members & visitors',18),
('st-francis-bay','St Francis Bay Golf Club','St Francis Bay','Eastern Cape','Members & visitors',18),
('the-belmont','The Belmont Golf Club','Makhanda','Eastern Cape','Members & visitors',18),
('uitenhage','Uitenhage Golf Club','Kariega','Eastern Cape','Members & visitors',18),
('avion-park','Avion Park Golf Club','Kempton Park','Gauteng','Members & visitors',9),
('cullinan','Cullinan Golf Club','Cullinan','Gauteng','Members & visitors',9),
('daveyton','Daveyton Golf Club','Daveyton','Gauteng','Members & visitors',9),
('heidelberg-gauteng','Heidelberg Golf Club','Heidelberg','Gauteng','Members & visitors',9),
('hillside','Hillside Golf Club','Randfontein','Gauteng','Members & visitors',9),
('sandonia','Sandonia Golf Club','Muldersdrift','Gauteng','Members & visitors',9),
('saps-training-centre','SAPS Training Centre Golf Club','Pretoria','Gauteng','Members & visitors',9),
('waterpan','Waterpan Golf Club','Carletonville','Gauteng','Members & visitors',9),
('zwartkop-afb','Zwartkop Golf Club (AFB)','Centurion','Gauteng','Members & visitors',9),
('amandelbult','Amandelbult Golf Club','Thabazimbi','Limpopo','Members & visitors',9),
('chrome','Chrome Golf Club','Steelpoort','Limpopo','Members & visitors',9),
('drakensig','Drakensig Golf Club','Hoedspruit','Limpopo','Members & visitors',9),
('groblersdal','Groblersdal Golf Club','Groblersdal','Limpopo','Members & visitors',9),
('marble-hall','Marble Hall Golf Club','Marble Hall','Limpopo','Members & visitors',9),
('messina','Messina Golf Club','Musina','Limpopo','Members & visitors',9),
('naboomspruit','Naboomspruit Golf Club','Mookgophong','Limpopo','Members & visitors',9),
('sesambos','Sesambos Golf Club','Tzaneen','Limpopo','Members & visitors',9),
('soutpansberg','Soutpansberg Golf Club','Makhado','Limpopo','Members & visitors',9),
('swartklip','Swartklip Golf Club','Northam','Limpopo','Members & visitors',9),
('thabazimbi','Thabazimbi Golf Club','Thabazimbi','Limpopo','Members & visitors',9),
('university-of-limpopo','University of Limpopo Golf Club','Mankweng','Limpopo','Members & visitors',9),
('amersfoort','Amersfoort Golf Club','Amersfoort','Mpumalanga','Members & visitors',9),
('arnot','Arnot Golf Club','Arnot','Mpumalanga','Members & visitors',9),
('badplaas','Badplaas Golf Club','Badplaas','Mpumalanga','Members & visitors',9),
('bankenveld','Bankenveld Golf Club','eMalahleni','Mpumalanga','Members & visitors',9),
('barberton','Barberton Golf Club','Barberton','Mpumalanga','Members & visitors',9),
('belfast','Belfast Golf Club','Belfast','Mpumalanga','Members & visitors',9),
('bethal','Bethal Golf Club','Bethal','Mpumalanga','Members & visitors',9),
('carolina','Carolina Golf Club','Carolina','Mpumalanga','Members & visitors',9),
('delmas','Delmas Golf Club','Delmas','Mpumalanga','Members & visitors',9),
('greenside','Greenside Golf Club','Standerton','Mpumalanga','Members & visitors',9),
('kambaku','Kambaku Golf Club','Komatipoort','Mpumalanga','Members & visitors',9),
('kranspoort','Kranspoort Golf Club','Machadodorp','Mpumalanga','Members & visitors',9),
('kriel','Kriel Golf Club','Kriel','Mpumalanga','Members & visitors',9),
('kruger-lodge','Kruger Lodge Golf Club','Malelane','Mpumalanga','Members & visitors',9),
('lydenburg','Lydenburg Golf Club','Lydenburg','Mpumalanga','Members & visitors',9),
('malelane','Malelane Golf Club','Malelane','Mpumalanga','Members & visitors',9),
('morgenzon','Morgenzon Golf Club','Morgenzon','Mpumalanga','Members & visitors',9),
('piet-retief','Piet Retief Golf Club','Piet Retief','Mpumalanga','Members & visitors',9),
('pilgrims-rest','Pilgrims Rest Golf Club','Pilgrims Rest','Mpumalanga','Members & visitors',9),
('sabie','Sabie Country Club','Sabie','Mpumalanga','Members & visitors',9),
('skukuza','Skukuza Golf Club','Skukuza','Mpumalanga','Members & visitors',9),
('standerton','Standerton Golf Club','Standerton','Mpumalanga','Members & visitors',9),
('volksrust','Volksrust Golf Club','Volksrust','Mpumalanga','Members & visitors',9),
('bloemhof','Bloemhof Golf Club','Bloemhof','North West','Members & visitors',9),
('christiana','Christiana Golf Club','Christiana','North West','Members & visitors',9),
('delareyville','Delareyville Golf Club','Delareyville','North West','Members & visitors',9),
('koster','Koster Golf Club','Koster','North West','Members & visitors',9),
('landboukollege','Landboukollege Golf Club','Potchefstroom','North West','Members & visitors',9),
('lichtenburg','Lichtenburg Golf Club','Lichtenburg','North West','Members & visitors',9),
('mooinooi','Mooinooi Golf Club','Mooinooi','North West','Members & visitors',9),
('ottosdal','Ottosdal Golf Club','Ottosdal','North West','Members & visitors',9),
('reivilo','Reivilo Golf Club','Reivilo','North West','Members & visitors',9),
('sandy-lane','Sandy Lane Golf Club','Brits','North West','Members & visitors',9),
('sannieshof','Sannieshof Golf Club','Sannieshof','North West','Members & visitors',9),
('schweizer-reneke','Schweizer-Reneke Golf Club','Schweizer-Reneke','North West','Members & visitors',9),
('ventersdorp','Ventersdorp Golf Club','Ventersdorp','North West','Members & visitors',9),
('vryburg','Vryburg Golf Club','Vryburg','North West','Members & visitors',9),
('wolmaransstad','Wolmaransstad Golf Club','Wolmaransstad','North West','Members & visitors',9),
('zeerust','Zeerust Golf Club','Zeerust','North West','Members & visitors',9),
('balkfontein','Balkfontein Golf Club','Bothaville','Free State','Members & visitors',9),
('bethulie','Bethulie Golf Club','Bethulie','Free State','Members & visitors',9),
('bothaville','Bothaville Golf Club','Bothaville','Free State','Members & visitors',9),
('brandfort','Brandfort Golf Club','Brandfort','Free State','Members & visitors',9),
('bultfontein','Bultfontein Golf Club','Bultfontein','Free State','Members & visitors',9),
('clocolan','Clocolan Golf Club','Clocolan','Free State','Members & visitors',9),
('dewetsdorp','Dewetsdorp Golf Club','Dewetsdorp','Free State','Members & visitors',9),
('edenburg','Edenburg Golf Club','Edenburg','Free State','Members & visitors',9),
('frankfort','Frankfort Golf Club','Frankfort','Free State','Members & visitors',9),
('heilbron','Heilbron Golf Club','Heilbron','Free State','Members & visitors',9),
('hoopstad','Hoopstad Golf Club','Hoopstad','Free State','Members & visitors',9),
('jacobsdal','Jacobsdal Golf Club','Jacobsdal','Free State','Members & visitors',9),
('jagersfontein','Jagersfontein Golf Club','Jagersfontein','Free State','Members & visitors',9),
('kestell','Kestell Golf Club','Kestell','Free State','Members & visitors',9),
('koffiefontein','Koffiefontein Golf Club','Koffiefontein','Free State','Members & visitors',9),
('marquard','Marquard Golf Club','Marquard','Free State','Members & visitors',9),
('maseru','Maseru Golf Club','Maseru (Lesotho)','Free State','Members & visitors',9),
('petrus-steyn','Petrus Steyn Golf Club','Petrus Steyn','Free State','Members & visitors',9),
('reitz','Reitz Golf Club','Reitz','Free State','Members & visitors',9),
('sand-river','Sand River Golf Club','Virginia','Free State','Members & visitors',9),
('senekal','Senekal Golf Club','Senekal','Free State','Members & visitors',9),
('smithfield','Smithfield Golf Club','Smithfield','Free State','Members & visitors',9),
('tempe','Tempe Golf Club','Bloemfontein','Free State','Members & visitors',9),
('theunissen','Theunissen Golf Club','Theunissen','Free State','Members & visitors',9),
('viljoenskroon','Viljoenskroon Golf Club','Viljoenskroon','Free State','Members & visitors',9),
('vrede','Vrede Golf Club','Vrede','Free State','Members & visitors',9),
('wesselsbron','Wesselsbron Golf Club','Wesselsbron','Free State','Members & visitors',9),
('westminster','Westminster Golf Club','Westminster','Free State','Members & visitors',9),
('zastron','Zastron Golf Club','Zastron','Free State','Members & visitors',9),
('alexander-bay','Alexander Bay Golf Club','Alexander Bay','Northern Cape','Members & visitors',9),
('arendskraal','Arendskraal Golf Club','Kathu','Northern Cape','Members & visitors',9),
('black-mountain','Black Mountain Golf Club','Aggeneys','Northern Cape','Members & visitors',9),
('colesberg','Colesberg Golf Club','Colesberg','Northern Cape','Members & visitors',9),
('de-aar','De Aar Golf Club','De Aar','Northern Cape','Members & visitors',9),
('douglas','Douglas Golf Club','Douglas','Northern Cape','Members & visitors',9),
('hartswater','Hartswater Golf Club','Hartswater','Northern Cape','Members & visitors',9),
('hopetown','Hopetown Golf Club','Hopetown','Northern Cape','Members & visitors',9),
('hotazel','Hotazel Golf Club','Hotazel','Northern Cape','Members & visitors',9),
('jan-kemp','Jan Kemp Golf Club','Jan Kempdorp','Northern Cape','Members & visitors',9),
('kakamas','Kakamas Golf Club','Kakamas','Northern Cape','Members & visitors',9),
('kleinzee','Kleinzee Golf Club','Kleinzee','Northern Cape','Members & visitors',9),
('kuruman','Kuruman Golf Club','Kuruman','Northern Cape','Members & visitors',9),
('lime-acres','Lime Acres Golf Club','Lime Acres','Northern Cape','Members & visitors',9),
('loeriesfontein','Loeriesfontein Golf Club','Loeriesfontein','Northern Cape','Members & visitors',9),
('prieska','Prieska Golf Club','Prieska','Northern Cape','Members & visitors',9),
('richmond-northern-cape','Richmond Golf Club','Richmond','Northern Cape','Members & visitors',9),
('springbok','Springbok Golf Club','Springbok','Northern Cape','Members & visitors',9),
('ulco','Ulco Golf Club','Ulco','Northern Cape','Members & visitors',9),
('williston','Williston Golf Club','Williston','Northern Cape','Members & visitors',9),
('berg-river','Berg River Golf Club','Paarl','Western Cape','Members & visitors',9),
('bonnievale','Bonnievale Golf Club','Bonnievale','Western Cape','Members & visitors',9),
('boschenmeer','Boschenmeer Golf Estate','Paarl','Western Cape','Members & visitors',9),
('bredasdorp','Bredasdorp Golf Club','Bredasdorp','Western Cape','Members & visitors',9),
('caledon','Caledon Golf Club','Caledon','Western Cape','Members & visitors',9),
('ceres','Ceres Golf Club','Ceres','Western Cape','Members & visitors',9),
('citrusdal','Citrusdal Golf Club','Citrusdal','Western Cape','Members & visitors',9),
('clanwilliam','Clanwilliam Golf Club','Clanwilliam','Western Cape','Members & visitors',9),
('darling','Darling Golf Club','Darling','Western Cape','Members & visitors',9),
('de-hoek','De Hoek Golf Club','Tulbagh','Western Cape','Members & visitors',9),
('gansbaai','Gansbaai Golf Club','Gansbaai','Western Cape','Members & visitors',9),
('hex-valley','Hex Valley Golf Club','De Doorns','Western Cape','Members & visitors',9),
('kleinmond','Kleinmond Golf Club','Kleinmond','Western Cape','Members & visitors',9),
('lamberts-bay','Lamberts Bay Golf Club','Lamberts Bay','Western Cape','Members & visitors',9),
('lutzville','Lutzville Golf Club','Lutzville','Western Cape','Members & visitors',9),
('malmesbury','Malmesbury Golf Club','Malmesbury','Western Cape','Members & visitors',9),
('montagu','Montagu Golf Club','Montagu','Western Cape','Members & visitors',9),
('moorreesburg','Moorreesburg Golf Club','Moorreesburg','Western Cape','Members & visitors',9),
('porterville','Porterville Golf Club','Porterville','Western Cape','Members & visitors',9),
('riverside','Riverside Golf Club','Robertson','Western Cape','Members & visitors',9),
('riviersonderend','Riviersonderend Golf Club','Riviersonderend','Western Cape','Members & visitors',9),
('shelley-point','Shelley Point Country Club','St Helena Bay','Western Cape','Members & visitors',9),
('swellendam','Swellendam Golf Club','Swellendam','Western Cape','Members & visitors',9),
('theewaterskloof','Theewaterskloof Golf Club','Villiersdorp','Western Cape','Members & visitors',9),
('vredenburg','Vredenburg Golf Club','Vredenburg','Western Cape','Members & visitors',9),
('vredendal','Vredendal Golf Club','Vredendal','Western Cape','Members & visitors',9),
('wellington','Wellington Golf Club','Wellington','Western Cape','Members & visitors',9),
('xamarin','Xamarin Golf Club','Tulbagh','Western Cape','Members & visitors',9),
('albertinia','Albertinia Golf Club','Albertinia','Western Cape','Members & visitors',9),
('beaufort-west','Beaufort West Golf Club','Beaufort West','Western Cape','Members & visitors',9),
('boggomsbaai','Boggomsbaai Golf Club','Boggomsbaai','Western Cape','Members & visitors',9),
('dolphin-creek','Dolphin Creek Golf Club','Groot Brakrivier','Western Cape','Members & visitors',9),
('glenwood','Glenwood Golf Club','George','Western Cape','Members & visitors',9),
('heidelberg-western-cape','Heidelberg Golf Club','Heidelberg','Western Cape','Members & visitors',9),
('ladismith','Ladismith Golf Club','Ladismith','Western Cape','Members & visitors',9),
('riversdale','Riversdale Golf Club','Riversdale','Western Cape','Members & visitors',9),
('stilbaai','Stilbaai Golf Club','Stilbaai','Western Cape','Members & visitors',9),
('uniondale','Uniondale Golf Club','Uniondale','Western Cape','Members & visitors',9),
('willowmore','Willowmore Golf Club','Willowmore','Western Cape','Members & visitors',9),
('fairview','Fairview Golf Club','Cape Town','Western Cape','Members & visitors',9),
('helderberg-village','Helderberg Village Golf Club','Somerset West','Western Cape','Members & visitors',9),
('metropolitan','Metropolitan Golf Club','Cape Town','Western Cape','Members & visitors',9),
('simonstown','Simonstown Country Club','Simons Town','Western Cape','Members & visitors',9),
('amatikulu','Amatikulu Golf Club','Amatikulu','KwaZulu-Natal','Members & visitors',9),
('amphitheatre','Amphitheatre Golf Club','Bergville','KwaZulu-Natal','Members & visitors',9),
('beachwood','Beachwood Golf Club','Durban','KwaZulu-Natal','Members & visitors',9),
('bosch-hoek','Bosch Hoek Golf Club','Balgowan','KwaZulu-Natal','Members & visitors',9),
('camelot','Camelot Golf Estate','Mooi River','KwaZulu-Natal','Members & visitors',9),
('cathedral-peak','Cathedral Peak Golf Club','Winterton','KwaZulu-Natal','Members & visitors',9),
('darnall','Darnall Country Club','Darnall','KwaZulu-Natal','Members & visitors',9),
('estcourt','Estcourt Golf Club','Estcourt','KwaZulu-Natal','Members & visitors',9),
('glencoe-correctional','Glencoe Correctional Golf Club','Glencoe','KwaZulu-Natal','Members & visitors',9),
('greytown','Greytown Country Club','Greytown','KwaZulu-Natal','Members & visitors',9),
('harding','Harding Country Club','Harding','KwaZulu-Natal','Members & visitors',9),
('howick','Howick Golf Club','Howick','KwaZulu-Natal','Members & visitors',9),
('kilbarchan','Kilbarchan Golf Club','Newcastle','KwaZulu-Natal','Members & visitors',9),
('kwambonambi','Kwambonambi Golf Club','KwaMbonambi','KwaZulu-Natal','Members & visitors',9),
('ladysmith','Ladysmith Golf Club','Ladysmith','KwaZulu-Natal','Members & visitors',13),
('maidstone','Maidstone Golf Club','Tongaat','KwaZulu-Natal','Members & visitors',9),
('mandini','Mandini Golf Club','Mandeni','KwaZulu-Natal','Members & visitors',9),
('melmoth','Melmoth Golf Club','Melmoth','KwaZulu-Natal','Members & visitors',9),
('monks-cowl','Monks Cowl Golf Club','Winterton','KwaZulu-Natal','Members & visitors',9),
('monzi','Monzi Golf Club','St Lucia','KwaZulu-Natal','Members & visitors',9),
('mooi-river-kzn','Mooi River Golf Club','Mooi River','KwaZulu-Natal','Members & visitors',9),
('mtunzini','Mtunzini Country Club','Mtunzini','KwaZulu-Natal','Members & visitors',9),
('noodsberg','Noodsberg Country Club','Dalton','KwaZulu-Natal','Members & visitors',9),
('paulpietersburg','Paulpietersburg Golf Club','Paulpietersburg','KwaZulu-Natal','Members & visitors',9),
('pongola','Pongola Golf Club','Pongola','KwaZulu-Natal','Members & visitors',9),
('port-edward','Port Edward Country Club','Port Edward','KwaZulu-Natal','Members & visitors',9),
('richmond-kzn','Richmond Country Club','Richmond','KwaZulu-Natal','Members & visitors',9),
('sakabula','Sakabula Golf Club','Howick','KwaZulu-Natal','Members & visitors',9),
('st-cathryns-country-estate','St Cathryns Country Estate','Hilton','KwaZulu-Natal','Members & visitors',9),
('umfolozi','Umfolozi Golf Club','Mtubatuba','KwaZulu-Natal','Members & visitors',9),
('underberg','Underberg Country Club','Underberg','KwaZulu-Natal','Members & visitors',9),
('utrecht','Utrecht Golf Club','Utrecht','KwaZulu-Natal','Members & visitors',9),
('vryheid','Vryheid Golf Club','Vryheid','KwaZulu-Natal','Members & visitors',9),
('adelaide','Adelaide Golf Club','Adelaide','Eastern Cape','Members & visitors',9),
('aliwal-north','Aliwal North Golf Club','Aliwal North','Eastern Cape','Members & visitors',9),
('barkly-east','Barkly East Golf Club','Barkly East','Eastern Cape','Members & visitors',9),
('bedford','Bedford Golf Club','Bedford','Eastern Cape','Members & visitors',9),
('burgersdorp','Burgersdorp Golf Club','Burgersdorp','Eastern Cape','Members & visitors',9),
('cathcart','Cathcart Golf Club','Cathcart','Eastern Cape','Members & visitors',9),
('cradock','Cradock Golf Club','Cradock','Eastern Cape','Members & visitors',9),
('dordrecht','Dordrecht Golf Club','Dordrecht','Eastern Cape','Members & visitors',9),
('elliot','Elliot Golf Club','Elliot','Eastern Cape','Members & visitors',9),
('fort-beaufort','Fort Beaufort Golf Club','Fort Beaufort','Eastern Cape','Members & visitors',9),
('gonubie','Gonubie Golf Club','Gonubie','Eastern Cape','Members & visitors',9),
('kei-mouth','Kei Mouth Golf Club','Kei Mouth','Eastern Cape','Members & visitors',9),
('komga','Komga Golf Club','Komga','Eastern Cape','Members & visitors',9),
('lady-grey','Lady Grey Golf Club','Lady Grey','Eastern Cape','Members & visitors',9),
('maclear','Maclear Golf Club','Maclear','Eastern Cape','Members & visitors',9),
('matatiele','Matatiele Golf Club','Matatiele','Eastern Cape','Members & visitors',9),
('middelburg-eastern-cape','Middelburg Golf Club','Middelburg','Eastern Cape','Members & visitors',9),
('molteno','Molteno Golf Club','Molteno','Eastern Cape','Members & visitors',9),
('port-st-johns','Port St Johns Golf Club','Port St Johns','Eastern Cape','Members & visitors',9),
('stutterheim','Stutterheim Golf Club','Stutterheim','Eastern Cape','Members & visitors',9),
('alexandria','Alexandria Golf Club','Alexandria','Eastern Cape','Members & visitors',9),
('fynbos','Fynbos Golf Club','Eersterivier','Eastern Cape','Members & visitors',9),
('graaff-reinet','Graaff-Reinet Golf Club','Graaff-Reinet','Eastern Cape','Members & visitors',9),
('hankey','Hankey Golf Club','Hankey','Eastern Cape','Members & visitors',9),
('jeffreys-bay','Jeffreys Bay Golf Club','Jeffreys Bay','Eastern Cape','Members & visitors',9),
('kirkwood','Kirkwood Golf Club','Kirkwood','Eastern Cape','Members & visitors',9),
('kragga-kamma','Kragga Kamma Golf Club','Gqeberha','Eastern Cape','Members & visitors',9),
('langkloof','Langkloof Golf Club','Kareedouw','Eastern Cape','Members & visitors',9),
('sardinia-bay','Sardinia Bay Golf Club','Gqeberha','Eastern Cape','Members & visitors',9),
('somerset-east','Somerset East Golf Club','Somerset East','Eastern Cape','Members & visitors',9),
('walmer','Walmer Country Club','Gqeberha','Eastern Cape','Members & visitors',9),
('walmer-golf-club','Walmer Golf Club','Gqeberha','Eastern Cape','Members & visitors',9),
('zwartenbosch','Zwartenbosch Golf Club','Loerie','Eastern Cape','Members & visitors',9)
on conflict (slug) do nothing;
