// Blog posts. To add a post: append an object here and it appears on /blog
// and in the sitemap automatically.

export const POSTS = [
  {
    slug: 'katberg-hidden-gem',
    title: 'South Africa\'s best-kept golf secret is up a mountain pass in the Eastern Cape',
    date: '2026-07-24',
    excerpt:
      'Katberg Eco Golf Estate sits nationally ranked in the top 100 courses in the country, deep in the Winterberg — and most golfers outside the Eastern Cape have never heard of it.',
    body: [
      { p: 'Ask ten South African golfers to name the country\'s best-kept secret and you\'ll get ten different answers, but here\'s a candidate that should be on every list: Katberg Eco Golf Estate, perched high in the Winterberg mountains outside Fort Beaufort, quietly sitting in the national top 100 while almost nobody outside the Eastern Cape can say they\'ve played it.' },
      { h: 'The course itself' },
      { p: 'This is a proper championship layout — par 72, kikuyu fairways, bent grass greens — laid out across an estate so large the golf is almost incidental to the setting. The fairways are narrow, the greens are sloped and quick, and the whole thing climbs and falls with the natural contours of the mountain rather than fighting them. The signature moment comes late: a waterfall tumbles between the 17th and 18th, which is either a lovely distraction or the worst possible time for your concentration to wander, depending on your scorecard.' },
      { h: 'A number that should turn heads' },
      { p: 'Top100GolfCourses.com — an international panel, not a local marketing exercise — currently places Katberg 95th nationally and 9th in the Eastern Cape. Ninth in a province that includes Humewood, St Francis Links and the Wild Coast Sun is no small thing for a course most Gauteng and Cape golfers couldn\'t point to on a map.' },
      { h: 'More than a round' },
      { p: 'Katberg is built as an eco-estate first, golf estate second, which means the round comes with company: a hiking trail up into the forest station above the course, trout fishing at nearby Thrift Dam, an equestrian centre, a spa, and self-catering villas positioned right on the fairways. It rewards the golfer willing to make a weekend of it rather than just ticking a box on a road trip.' },
      { h: 'Katberg isn\'t the only secret out there' },
      { p: 'South Africa is full of courses that punch above their profile, tucked into dorpies and valleys the ranking panels never visit. Here are four more worth a tank of petrol, from the Northern Cape to the West Coast.' },
      { h: 'Kimberley Golf Club — the diamond city original' },
      { p: 'One of the oldest golfing sites in the country, laid out in 1890 with Cecil John Rhodes among its early benefactors, and host of South Africa\'s very first Amateur Championship in 1892. Today it plays as a par-71 Bob Grimsdell parkland running on kikuyu through the old diamond fields, with the Freddie Tait Golf Museum in the clubhouse guarding more than a century of the game\'s history. The green fee is a fraction of what the big estates charge — and the sense of history is something none of them can buy.' },
      { h: 'Worcester Golf Club — mountains, vines and the best greens in the Cape' },
      { p: 'Tucked into the foothills of the Brandwacht Mountains in the Breede River Valley, this 1927 layout reworked by Peter Matkovich plays par 72 through vineyard country under a wall of rock. Regulars will tell you the putting surfaces are among the finest in the Western Cape, and the scenery does the rest. Gary Player once called it one of the finest courses in the world — high praise for a country club most Capetonians drive straight past on the N1.' },
      { h: 'Langebaan Country Estate — links-style golf on the lagoon' },
      { p: 'An hour up the West Coast from Cape Town, Langebaan is a par-72 Bill Kerr design reworked in 2006 by Gary Player\'s Black Knight team: waste bunkers, a big water feature splitting the 10th and 18th, natural rock and wildflowers, and the ever-present wind off the lagoon that means it never plays the same way twice. Views over the bay, birdlife everywhere, and a genuine test the moment the southeaster gets up.' },
      { h: 'Eagle Canyon Golf Estate — a course carved from a quarry' },
      { p: 'On the Roodepoort edge of Joburg, Douw van der Merwe turned an old sand quarry into a par-72 that tumbles along the canyon cliffs and over water, with a clubhouse perched on the high point looking down on all eighteen holes. It flies under the radar next to Gauteng\'s marquee names, but the drama of the setting and the quality of the conditioning put it firmly in gem territory.' },
      { h: 'Your verdict counts here' },
      { p: 'Katberg and every one of these is on Pin High, sitting on real ratings from real rounds rather than a panel\'s single visit. Played one of them? Your six categories — and a comment about what makes it special — will do more for the course\'s profile than any magazine feature. And if you haven\'t, consider this the nudge: some of the country\'s best golf is hiding exactly where you\'d least expect it.' },
    ],
  },
  {
    slug: 'garden-route-golf-trip',
    title: 'The Garden Route golf trip, rated: eleven courses in one glorious stretch',
    date: '2026-07-09',
    excerpt:
      'From Mossel Bay to Plettenberg Bay lies the densest run of quality golf in South Africa. Here\'s the route — and how golfers are rating every stop.',
    body: [
      { p: 'There is nowhere else in South Africa — arguably nowhere in the southern hemisphere — where you can play this much good golf in a 130-kilometre stretch. Between Mossel Bay and Plettenberg Bay sit eleven rateable courses, from a 19th-century clifftop classic to three of the country\'s most famous modern layouts. If you\'re planning the pilgrimage, here\'s the route west to east.' },
      { h: 'Mossel Bay to George' },
      { p: 'Start at Mossel Bay Golf Club, a friendly old clifftop course with sea views on nearly every hole, then swing past Pinnacle Point — the dramatic one, where several holes play across ocean gorges and your camera roll fills up faster than your scorecard. In George you hit the heavyweight cluster: George Golf Club, the tree-lined charmer locals will tell you is the best value in the region, Kingswood next door, and of course Fancourt, home to three courses — the resort-friendly Outeniqua, the stately Montagu, and The Links, currently sitting where it usually sits: at the top of the rankings.' },
      { h: 'Herolds Bay to Plett' },
      { p: 'Just down the coast, Oubaai brings Ernie Els\'s clifftop links style above Herolds Bay. Then it\'s on to Knysna: the town course down by the lagoon, Simola on the ridge above the valley (Nicklaus, staggering views), and Pezula out on the Heads, carved through fynbos. Finish at Goose Valley beside the Keurbooms lagoon and the Plettenberg Bay Country Club, where the 19th hole earns its keep.' },
      { h: 'The itinerary maths' },
      { p: 'Five days does it comfortably: two nights George, two nights Knysna, one in Plett, eleven courses if your body holds. Even the modest green fees down here buy conditions most inland courses can\'t match in winter — this is where South African golf goes on holiday.' },
      { h: 'Now the important part' },
      { p: 'Every course on this route is on Pin High, and the rankings are decided by the golfers who make this trip. Played the Garden Route recently? Rate every course you remember — thirty seconds each — and help settle the eternal bar argument: Links, Pinnacle Point or Simola? The rankings are keeping score.' },
    ],
  },
  {
    slug: 'small-town-nine-holers',
    title: 'In defence of the 9-holer: South Africa\'s small-town courses deserve your Sunday',
    date: '2026-07-09',
    excerpt:
      'More than 200 of South Africa\'s golf courses are small-town 9-holers — and almost none of them have ever been rated. Time to fix that.',
    body: [
      { p: 'Over half the golf courses in South Africa are 9-holers. Bethulie, Kakamas, Piet Retief, Lamberts Bay, Hotazel — places where the clubhouse honour bar runs on trust, the greens might be sand or might be the best-kept secret in the district, and a fourball costs less than a sleeve of premium balls. They are the backbone of South African golf, and they are almost completely invisible on every ranking that has ever been published.' },
      { h: 'What the panels never see' },
      { p: 'No rating panel is driving to Williston. But the golfers who play these courses know things the panels never will: which Karoo course has greens that putt truer than half of Gauteng\'s parklands, which Free State club serves the best steak in a hundred kilometres, which mining-town course is an oasis you\'d never believe until you\'ve seen it. Sishen made Golf Digest\'s national top ten precisely because someone finally went and looked — imagine what else is out there.' },
      { h: 'The Pioneer project' },
      { p: 'This is why the Pioneer badge exists. Hundreds of South African courses have never received a single rating on Pin High — most of them exactly these small-town 9-holers. Be the first golfer to rate one and the Pioneer badge is yours forever; claim ten and you\'re a Trailblazer. Your hometown course, your December-holidays course, the one your uncle swears by — all unclaimed, all waiting.' },
      { h: 'How to do it right' },
      { p: 'Rate them honestly, not sentimentally — value is where these courses shine, and the ratings should show it. Leave a comment with the local knowledge: honesty-box green fees, which day the mowers run, whether to phone ahead for a braai. And rate the 19th hole separately, because in the small towns the bar is half the institution. The big estates have marketing departments; these courses have you.' },
    ],
  },
  {
    slug: 'golf-digest-top-30-do-you-agree',
    title: 'Golf Digest just ranked South Africa\'s best courses. Do you agree?',
    date: '2026-07-08',
    excerpt:
      'Golf Digest\'s panel puts Fancourt Links first, Blair Atholl second and a Kalahari mining-town course in the top ten. Time for the golfers to weigh in.',
    body: [
      { p: 'Golf Digest has published its panel\'s ranking of the best golf courses in South Africa, and it\'s a fascinating read. The Links at Fancourt takes the number one spot — few will argue with Gary Player\'s manufactured links masterpiece. But scan down the list and the debates start almost immediately.' },
      { h: 'The talking points' },
      { p: 'Blair Atholl at number two. The panel clearly loves the scale of Player\'s 7,500-metre monster on the Crocodile River — but it\'s a private estate most golfers will never play, ranked above courses the whole country knows and loves. Pearl Valley completes their podium at three, with Durban Country Club — the course that\'s hosted more SA Opens than any other — at four, and Leopard Creek, the one many would instinctively put first, all the way down at five.' },
      { p: 'Then there\'s the pick we genuinely admire: Sishen Golf Club at number nine. A green oasis next to an iron-ore mine in Kathu, ranked above the Gary Player Country Club — the course that hosts Africa\'s biggest tournament. If you\'ve made the trek to the Northern Cape, you\'ll know the panel has a point. If you haven\'t, that\'s exactly the kind of ranking that starts arguments at the 19th.' },
      { p: 'Rounding out their top ten: Arabella at six, St Francis Links at seven, Glendower at eight, and the Gary Player Country Club at ten. Deeper down, Elements sneaks in at eleven ahead of Royal Johannesburg East, and humble Parkview closes out the thirty.' },
      { h: 'Here\'s the thing about panels' },
      { p: 'Golf Digest\'s raters are knowledgeable, well-travelled people, and their list is a serious piece of work. But it\'s still a few dozen opinions. It can\'t capture whether the visitors\' green fee felt fair, whether the fourball in front of you was waved through or ignored, whether the halfway house pie was worth stopping for, or whether the staff remembered your name the second time you visited. Those things decide where South African golfers actually spend their money — and no panel measures them.' },
      { h: 'Your verdict counts here' },
      { p: 'Every course on Golf Digest\'s list is on Pin High — along with the other 380-odd GolfRSA-affiliated courses their panel never visited. If you think Leopard Creek deserves the top spot, say so with a rating. If you think Durban CC is criminally underrated at four, fix it. If you\'ve played Sishen and the panel is spot on, back them up.' },
      { p: 'That\'s the whole idea of this site: the experts have had their say, now the golfers get theirs. Rate the courses you\'ve played — overall, value, conditions, layout, clubhouse and staff — and let\'s find out where the people\'s rankings and the panel\'s rankings disagree. Our money is on "everywhere".' },
    ],
  },
  {
    slug: 'why-we-built-pin-high',
    title: 'Why we built Pin High: golf rankings without the panels',
    date: '2026-07-07',
    excerpt:
      'Every golf ranking in South Africa is decided by a small panel of raters. We think the 139,000 golfers who actually play these courses every week deserve the vote instead.',
    body: [
      { p: 'Pick up any list of South Africa\'s best golf courses and somewhere in the fine print you\'ll find the same thing: a panel. A few dozen well-travelled raters, scoring courses against criteria you never see, producing a ranking you\'re meant to accept.' },
      { p: 'The panels aren\'t wrong, exactly. Leopard Creek is magnificent. The Links at Fancourt is a masterpiece. But panels have blind spots. They visit on invitation, play in perfect conditions, and get the good table at lunch. They don\'t queue for a Sunday tee time, pay their own green fee, or discover that the halfway house ran out of pies at 11am. The golfer\'s experience of a course — the one that decides whether you go back — is bigger than architecture.' },
      { h: 'One golfer, one vote' },
      { p: 'Pin High ranks every GolfRSA-affiliated course in the country — more than 400 — using ratings from golfers who\'ve actually played them. Six categories: overall, value, conditions, layout, clubhouse and staff. Every rating carries the same weight whether it comes from a scratch golfer or a 24 handicap, because both of them paid the same green fee.' },
      { p: 'The maths is simple and transparent: a course\'s position is the average of its golfer ratings, and every card shows how many ratings sit behind the score, so you can judge the sample for yourself. Early on, your opinion counts for a lot — every new rating genuinely moves the list.' },
      { h: 'What we\'re not' },
      { p: 'We\'re not a booking site, we don\'t take money from courses, and no club can pay to move up the list. If a course tops a Pin High ranking, it\'s because golfers put it there. If it props up the bottom, well — golfers put it there too, and the club knows exactly what to fix.' },
      { p: 'So that\'s the pitch. You\'ve got opinions about every course you\'ve ever played — the brilliant ones, the overpriced ones, the hidden gems nobody talks about. Sign up in thirty seconds and put them on the record. The rankings are yours to shape.' },
    ],
  },
  {
    slug: 'how-to-rate-a-golf-course',
    title: 'How to rate a golf course: what our six categories actually mean',
    date: '2026-07-07',
    excerpt:
      'Value, course condition, layout, halfway house, staff — a quick guide to what each Pin High rating category covers, and how to score like you mean it.',
    body: [
      { p: 'Rating a course on Pin High takes thirty seconds: six categories, one to five stars each, and an optional comment. But the rankings are only as good as the ratings behind them, so here\'s what each category is really asking.' },
      { h: 'Overall' },
      { p: 'You don\'t score this one — it\'s calculated automatically as the average of your six category ratings, and it\'s the number that drives the main rankings. Score the categories honestly and the overall takes care of itself.' },
      { h: 'Value' },
      { p: 'Not "was it cheap" — was it worth it. A R1,500 round can be five-star value and a R250 round can be a rip-off. Judge the experience against what you paid.' },
      { h: 'Course Condition' },
      { p: 'The course on the day you played it: fairways, tee boxes, bunkers, rough. Be fair — if you played mid-winter or a week after a festival, say so in your comment.' },
      { h: 'Greens' },
      { p: 'The putting surfaces get their own score, because golfers judge a course by them more than anything else. Speed, trueness, health — were they pure or were they punished?' },
      { h: 'Layout' },
      { p: 'The architecture. Variety, strategy, memorability. Could you describe three holes to a friend a month later? That\'s a good layout. Are all the par 4s the same hole in different directions? That\'s not.' },
      { h: 'Halfway House' },
      { p: 'The stop at the turn — the pie, the toasted sarmie, the cold drink, the speed of service. South African golf culture lives here, and a course that gets the turn right earns its stars honestly. (The 19th hole bar has its own separate rating.)' },
      { h: 'Staff' },
      { p: 'From the bag drop to the pro shop to the beverage cart. Friendly, sharp service turns a good day great; being treated like an inconvenience at your own booking does the opposite.' },
      { h: 'One habit worth building' },
      { p: 'Rate the course within a day or two of playing it, while the details are fresh — and drop one honest sentence in the comment. "Greens were the best I\'ve putted all year" tells the next golfer more than the stars do. One rating per course per golfer, and you can update yours any time your opinion changes. Now go rate the last course you played.' },
    ],
  },
  {
    slug: 'best-19th-holes-south-africa',
    title: 'The search for South Africa\'s best 19th hole starts now',
    date: '2026-07-07',
    excerpt:
      'The round is only half the story. Pin High now ranks SA\'s clubhouse bars and halfway houses — atmosphere, drinks, food, view and service. Nominate yours by rating it.',
    body: [
      { p: 'Ask a golfer about their favourite course and you\'ll hear about a back nine. Ask them about their favourite day of golf, and sooner or later the story ends up at the bar: the ice-cold lager after a 40-degree round in the bushveld, the pie at the halfway house that saved a collapsing card, the deck where you watched your fourball finish 18 in the sunset.' },
      { p: 'That\'s the 19th hole, and it\'s never had a ranking. Until now.' },
      { h: 'How it works' },
      { p: 'Every course page on Pin High now has a second rating panel for the 19th hole, scored on five things that matter after a round: atmosphere, drinks, food, view and service — plus your overall verdict. The votes build a separate national leaderboard at pinhigh.co.za/19th-holes, ranked the same way as the courses: by golfers, weighted by volume of votes, immune to marketing budgets.' },
      { p: 'The beauty of this list is that it has nothing to do with course pedigree. A 9-hole country club in the Free State with a legendary bar can outrank a championship estate with a soulless lounge. We suspect a few will.' },
      { h: 'The rules of a great 19th' },
      { p: 'We\'d argue the greats share a few things: beer served properly cold and priced like the club remembers you just paid a green fee; food that arrives fast and tastes like it was made for hungry golfers, not a wedding; a view of golf — ideally the 18th green, so you can heckle incoming fourballs; and staff who ask how you played and mean it.' },
      { p: 'You know the bars that qualify. Go to the course\'s page, scroll to "Rate the 19th hole", and get your favourite on the board. The title of South Africa\'s greatest 19th hole is officially up for grabs.' },
    ],
  },
];

export const getPost = (slug) => POSTS.find((p) => p.slug === slug);
